version: '3'

services:
  db:
    image: postgres:15-alpine
    volumes:
      - data:/var/lib/postgresql
    networks:
      - mynetwork
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespw
      POSTGRES_DB: portfoliodb
      POSTGRES_HOST: db
    ports:
      - 5432:5432
  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PG_PORT: 5432
      PG_USER: postgres
      PG_PASSWORD: postgrespw
      PG_DATABASE: portfoliodb
      PG_HOST: db
      PORT: 8080
      SIGNATURE_KEY: sonfolioSignatureBySunchiii@github.com
      TOKEN_EXP: 24
    ports:
      - "8080:8080"
    networks:
      - mynetwork
    restart: always
    depends_on:
      - db
    links:
      - db
volumes:
  data:
networks:
  mynetwork: 
    driver: bridge
